create table dbo.permissions (permission_id bigint identity not null, permission_name varchar(255) not null, primary key (permission_id));
create table dbo.role_permissions (id bigint identity not null, permission_id bigint, role_id bigint, primary key (id));
create table dbo.user_permissions (id bigint identity not null, permission_id bigint not null, user_id bigint, primary key (id));
create table dbo.user_refresh_tokens (expiry_date datetimeoffset(6) not null, id bigint identity not null, user_id bigint not null, token varchar(255) not null, primary key (id));
alter table dbo.permissions add constraint UKnry1f3jmc4abb5yvkftlvn6vg unique (permission_name);
alter table dbo.user_refresh_tokens add constraint UKtaaxjuy6au86lbi8yd3c6m89u unique (user_id);
alter table dbo.user_refresh_tokens add constraint UKsxox5iemytmg28rv45sq1rgvo unique (token);
create table companies (created_by int, company_id bigint identity not null, created_at datetimeoffset(6), company_hotline_accident varchar(20), company_hotline_sale varchar(20), company_phone_number varchar(20), company_address varchar(255), company_email varchar(255), company_name varchar(255) not null, company_website varchar(255), primary key (company_id));
create table role_permissions (permission_id bigint not null, role_id bigint not null, primary key (permission_id, role_id));
create table roles (role_id bigint identity not null, role_name varchar(255) not null, primary key (role_id));
create table user_permissions (permission_id bigint not null, user_id bigint not null, primary key (permission_id, user_id));
create table user_roles (id bigint identity not null, role_id bigint, user_id bigint, primary key (id));
create table users (is_enabled bit not null, company_id bigint not null, created_at datetime2(6), parent_id bigint, updated_at datetime2(6), user_id bigint identity not null, phone_number varchar(20), username varchar(100) not null, email varchar(255) not null, password varchar(255) not null, primary key (user_id));
alter table companies add constraint UKhj46lf87q00ohfd02njib276u unique (company_name);
alter table roles add constraint UK716hgxp60ym1lifrdgp67xt5k unique (role_name);
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table dbo.role_permissions add constraint FK_role_permissions_permission_id foreign key (permission_id) references dbo.permissions;
alter table dbo.role_permissions add constraint FK_role_permissions_role_id foreign key (role_id) references roles;
alter table dbo.user_permissions add constraint FK_user_permissions_permission_id foreign key (permission_id) references dbo.permissions;
alter table dbo.user_permissions add constraint FK_user_permissions_user_id foreign key (user_id) references users;
alter table dbo.user_refresh_tokens add constraint FKkhknsfl0u6m4ocx8k2p6b4hkr foreign key (user_id) references users;
alter table role_permissions add constraint FKegdk29eiy7mdtefy5c7eirr6e foreign key (permission_id) references dbo.permissions;
alter table role_permissions add constraint FKn5fotdgk8d1xvo8nav9uv3muc foreign key (role_id) references roles;
alter table user_permissions add constraint FKq4qlrabt4s0etm9tfkoqfuib1 foreign key (permission_id) references dbo.permissions;
alter table user_permissions add constraint FKkowxl8b2bngrxd1gafh13005u foreign key (user_id) references users;
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles;
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users;
alter table users add constraint FKin8gn4o1hpiwe6qe4ey7ykwq7 foreign key (company_id) references companies;
alter table users add constraint FK4ty2qb76gscl4oi0yugg5gywc foreign key (parent_id) references users;
create table dbo.permissions (permission_id bigint identity not null, permission_name varchar(255) not null, primary key (permission_id));
create table dbo.role_permissions (id bigint identity not null, permission_id bigint, role_id bigint, primary key (id));
create table dbo.user_permissions (id bigint identity not null, permission_id bigint not null, user_id bigint, primary key (id));
create table dbo.user_refresh_tokens (expiry_date datetimeoffset(6) not null, id bigint identity not null, user_id bigint not null, token varchar(255) not null, primary key (id));
alter table dbo.permissions add constraint UKnry1f3jmc4abb5yvkftlvn6vg unique (permission_name);
alter table dbo.user_refresh_tokens add constraint UKtaaxjuy6au86lbi8yd3c6m89u unique (user_id);
alter table dbo.user_refresh_tokens add constraint UKsxox5iemytmg28rv45sq1rgvo unique (token);
create table companies (created_by int, company_id bigint identity not null, created_at datetimeoffset(6), company_hotline_accident varchar(20), company_hotline_sale varchar(20), company_phone_number varchar(20), company_address varchar(255), company_email varchar(255), company_name varchar(255) not null, company_website varchar(255), primary key (company_id));
create table role_permissions (permission_id bigint not null, role_id bigint not null, primary key (permission_id, role_id));
create table roles (role_id bigint identity not null, role_name varchar(255) not null, primary key (role_id));
create table user_permissions (permission_id bigint not null, user_id bigint not null, primary key (permission_id, user_id));
create table user_roles (id bigint identity not null, role_id bigint, user_id bigint, primary key (id));
create table users (is_enabled bit not null, company_id bigint not null, created_at datetime2(6), parent_id bigint, updated_at datetime2(6), user_id bigint identity not null, phone_number varchar(20), username varchar(100) not null, email varchar(255) not null, password varchar(255) not null, primary key (user_id));
alter table companies add constraint UKhj46lf87q00ohfd02njib276u unique (company_name);
alter table roles add constraint UK716hgxp60ym1lifrdgp67xt5k unique (role_name);
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table dbo.role_permissions add constraint FK_role_permissions_permission_id foreign key (permission_id) references dbo.permissions;
alter table dbo.role_permissions add constraint FK_role_permissions_role_id foreign key (role_id) references roles;
alter table dbo.user_permissions add constraint FK_user_permissions_permission_id foreign key (permission_id) references dbo.permissions;
alter table dbo.user_permissions add constraint FK_user_permissions_user_id foreign key (user_id) references users;
alter table dbo.user_refresh_tokens add constraint FKkhknsfl0u6m4ocx8k2p6b4hkr foreign key (user_id) references users;
alter table role_permissions add constraint FKegdk29eiy7mdtefy5c7eirr6e foreign key (permission_id) references dbo.permissions;
alter table role_permissions add constraint FKn5fotdgk8d1xvo8nav9uv3muc foreign key (role_id) references roles;
alter table user_permissions add constraint FKq4qlrabt4s0etm9tfkoqfuib1 foreign key (permission_id) references dbo.permissions;
alter table user_permissions add constraint FKkowxl8b2bngrxd1gafh13005u foreign key (user_id) references users;
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles;
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users;
alter table users add constraint FKin8gn4o1hpiwe6qe4ey7ykwq7 foreign key (company_id) references companies;
alter table users add constraint FK4ty2qb76gscl4oi0yugg5gywc foreign key (parent_id) references users;
create table dbo.permissions (permission_id bigint identity not null, permission_name varchar(255) not null, primary key (permission_id));
create table dbo.role_permissions (id bigint identity not null, permission_id bigint, role_id bigint, primary key (id));
create table dbo.user_permissions (id bigint identity not null, permission_id bigint not null, user_id bigint, primary key (id));
create table dbo.user_refresh_tokens (expiry_date datetimeoffset(6) not null, id bigint identity not null, user_id bigint not null, token varchar(255) not null, primary key (id));
alter table dbo.permissions add constraint UKnry1f3jmc4abb5yvkftlvn6vg unique (permission_name);
alter table dbo.user_refresh_tokens add constraint UKtaaxjuy6au86lbi8yd3c6m89u unique (user_id);
alter table dbo.user_refresh_tokens add constraint UKsxox5iemytmg28rv45sq1rgvo unique (token);
create table companies (created_by int, company_id bigint identity not null, created_at datetimeoffset(6), company_hotline_accident varchar(20), company_hotline_sale varchar(20), company_phone_number varchar(20), company_address varchar(255), company_email varchar(255), company_name varchar(255) not null, company_website varchar(255), primary key (company_id));
create table role_permissions (permission_id bigint not null, role_id bigint not null, primary key (permission_id, role_id));
create table roles (role_id bigint identity not null, role_name varchar(255) not null, primary key (role_id));
create table user_permissions (permission_id bigint not null, user_id bigint not null, primary key (permission_id, user_id));
create table user_roles (id bigint identity not null, role_id bigint, user_id bigint, primary key (id));
create table users (is_enabled bit not null, company_id bigint not null, created_at datetime2(6), parent_id bigint, updated_at datetime2(6), user_id bigint identity not null, phone_number varchar(20), username varchar(100) not null, email varchar(255) not null, password varchar(255) not null, primary key (user_id));
alter table companies add constraint UKhj46lf87q00ohfd02njib276u unique (company_name);
alter table roles add constraint UK716hgxp60ym1lifrdgp67xt5k unique (role_name);
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table dbo.role_permissions add constraint FK_role_permissions_permission_id foreign key (permission_id) references dbo.permissions;
alter table dbo.role_permissions add constraint FK_role_permissions_role_id foreign key (role_id) references roles;
alter table dbo.user_permissions add constraint FK_user_permissions_permission_id foreign key (permission_id) references dbo.permissions;
alter table dbo.user_permissions add constraint FK_user_permissions_user_id foreign key (user_id) references users;
alter table dbo.user_refresh_tokens add constraint FKkhknsfl0u6m4ocx8k2p6b4hkr foreign key (user_id) references users;
alter table role_permissions add constraint FKegdk29eiy7mdtefy5c7eirr6e foreign key (permission_id) references dbo.permissions;
alter table role_permissions add constraint FKn5fotdgk8d1xvo8nav9uv3muc foreign key (role_id) references roles;
alter table user_permissions add constraint FKq4qlrabt4s0etm9tfkoqfuib1 foreign key (permission_id) references dbo.permissions;
alter table user_permissions add constraint FKkowxl8b2bngrxd1gafh13005u foreign key (user_id) references users;
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles;
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users;
alter table users add constraint FKin8gn4o1hpiwe6qe4ey7ykwq7 foreign key (company_id) references companies;
alter table users add constraint FK4ty2qb76gscl4oi0yugg5gywc foreign key (parent_id) references users;
create table dbo.permissions (permission_id bigint identity not null, permission_name varchar(255) not null, primary key (permission_id));
create table dbo.role_permissions (id bigint identity not null, permission_id bigint, role_id bigint, primary key (id));
create table dbo.user_permissions (id bigint identity not null, permission_id bigint not null, user_id bigint, primary key (id));
create table dbo.user_refresh_tokens (expiry_date datetimeoffset(6) not null, id bigint identity not null, user_id bigint not null, token varchar(255) not null, primary key (id));
alter table dbo.permissions add constraint UKnry1f3jmc4abb5yvkftlvn6vg unique (permission_name);
alter table dbo.user_refresh_tokens add constraint UKtaaxjuy6au86lbi8yd3c6m89u unique (user_id);
alter table dbo.user_refresh_tokens add constraint UKsxox5iemytmg28rv45sq1rgvo unique (token);
create table companies (created_by int, company_id bigint identity not null, created_at datetimeoffset(6), company_hotline_accident varchar(20), company_hotline_sale varchar(20), company_phone_number varchar(20), company_address varchar(255), company_email varchar(255), company_name varchar(255) not null, company_website varchar(255), primary key (company_id));
create table role_permissions (permission_id bigint not null, role_id bigint not null, primary key (permission_id, role_id));
create table roles (role_id bigint identity not null, role_name varchar(255) not null, primary key (role_id));
create table user_permissions (permission_id bigint not null, user_id bigint not null, primary key (permission_id, user_id));
create table user_roles (id bigint identity not null, role_id bigint, user_id bigint, primary key (id));
create table users (is_enabled bit not null, company_id bigint not null, created_at datetime2(6), parent_id bigint, updated_at datetime2(6), user_id bigint identity not null, phone_number varchar(20), username varchar(100) not null, email varchar(255) not null, password varchar(255) not null, primary key (user_id));
alter table companies add constraint UKhj46lf87q00ohfd02njib276u unique (company_name);
alter table roles add constraint UK716hgxp60ym1lifrdgp67xt5k unique (role_name);
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table dbo.role_permissions add constraint FK_role_permissions_permission_id foreign key (permission_id) references dbo.permissions;
alter table dbo.role_permissions add constraint FK_role_permissions_role_id foreign key (role_id) references roles;
alter table dbo.user_permissions add constraint FK_user_permissions_permission_id foreign key (permission_id) references dbo.permissions;
alter table dbo.user_permissions add constraint FK_user_permissions_user_id foreign key (user_id) references users;
alter table dbo.user_refresh_tokens add constraint FKkhknsfl0u6m4ocx8k2p6b4hkr foreign key (user_id) references users;
alter table role_permissions add constraint FKegdk29eiy7mdtefy5c7eirr6e foreign key (permission_id) references dbo.permissions;
alter table role_permissions add constraint FKn5fotdgk8d1xvo8nav9uv3muc foreign key (role_id) references roles;
alter table user_permissions add constraint FKq4qlrabt4s0etm9tfkoqfuib1 foreign key (permission_id) references dbo.permissions;
alter table user_permissions add constraint FKkowxl8b2bngrxd1gafh13005u foreign key (user_id) references users;
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles;
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users;
alter table users add constraint FKin8gn4o1hpiwe6qe4ey7ykwq7 foreign key (company_id) references companies;
alter table users add constraint FK4ty2qb76gscl4oi0yugg5gywc foreign key (parent_id) references users;
create table dbo.permissions (permission_id bigint identity not null, permission_name varchar(255) not null, primary key (permission_id));
create table dbo.role_permissions (id bigint identity not null, permission_id bigint, role_id bigint, primary key (id));
create table dbo.user_permissions (id bigint identity not null, permission_id bigint not null, user_id bigint, primary key (id));
create table dbo.user_refresh_tokens (expiry_date datetimeoffset(6) not null, id bigint identity not null, user_id bigint not null, token varchar(255) not null, primary key (id));
alter table dbo.permissions add constraint UKnry1f3jmc4abb5yvkftlvn6vg unique (permission_name);
alter table dbo.user_refresh_tokens add constraint UKtaaxjuy6au86lbi8yd3c6m89u unique (user_id);
alter table dbo.user_refresh_tokens add constraint UKsxox5iemytmg28rv45sq1rgvo unique (token);
create table companies (created_by int, company_id bigint identity not null, created_at datetimeoffset(6), company_hotline_accident varchar(20), company_hotline_sale varchar(20), company_phone_number varchar(20), company_address varchar(255), company_email varchar(255), company_name varchar(255) not null, company_website varchar(255), primary key (company_id));
create table role_permissions (permission_id bigint not null, role_id bigint not null, primary key (permission_id, role_id));
create table roles (role_id bigint identity not null, role_name varchar(255) not null, primary key (role_id));
create table user_permissions (permission_id bigint not null, user_id bigint not null, primary key (permission_id, user_id));
create table user_roles (id bigint identity not null, role_id bigint, user_id bigint, primary key (id));
create table users (is_enabled bit not null, company_id bigint not null, created_at datetime2(6), parent_id bigint, updated_at datetime2(6), user_id bigint identity not null, phone_number varchar(20), username varchar(100) not null, email varchar(255) not null, password varchar(255) not null, primary key (user_id));
alter table companies add constraint UKhj46lf87q00ohfd02njib276u unique (company_name);
alter table roles add constraint UK716hgxp60ym1lifrdgp67xt5k unique (role_name);
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table dbo.role_permissions add constraint FK_role_permissions_permission_id foreign key (permission_id) references dbo.permissions;
alter table dbo.role_permissions add constraint FK_role_permissions_role_id foreign key (role_id) references roles;
alter table dbo.user_permissions add constraint FK_user_permissions_permission_id foreign key (permission_id) references dbo.permissions;
alter table dbo.user_permissions add constraint FK_user_permissions_user_id foreign key (user_id) references users;
alter table dbo.user_refresh_tokens add constraint FKkhknsfl0u6m4ocx8k2p6b4hkr foreign key (user_id) references users;
alter table role_permissions add constraint FKegdk29eiy7mdtefy5c7eirr6e foreign key (permission_id) references dbo.permissions;
alter table role_permissions add constraint FKn5fotdgk8d1xvo8nav9uv3muc foreign key (role_id) references roles;
alter table user_permissions add constraint FKq4qlrabt4s0etm9tfkoqfuib1 foreign key (permission_id) references dbo.permissions;
alter table user_permissions add constraint FKkowxl8b2bngrxd1gafh13005u foreign key (user_id) references users;
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles;
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users;
alter table users add constraint FKin8gn4o1hpiwe6qe4ey7ykwq7 foreign key (company_id) references companies;
alter table users add constraint FK4ty2qb76gscl4oi0yugg5gywc foreign key (parent_id) references users;
